apps/home/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import HomeView, HomeMoviesView, MoviesCategoryView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('movies/', HomeMoviesView.as_view(), name='movies'),
    path('movies/<int:pk>', HomeMoviesView.as_view(), name='movies'),
    path('category/', MoviesCategoryView.as_view(), name="category"),
    path('category/<int:pk>', MoviesCategoryView.as_view(), name="category"),
    # path(
    #     'category/ajax/get_category_id',
    #     'MoviesCategoryView.get_category_id',
    #     name="category_ajax"
    # ),
]

mongo_test/urls.py
# -*- coding: utf-8 -*-
"""mongo_test URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls', 'home')),
    path('fontawesome/', include("django_static_fontawesome.urls")),
]

apps/home/models.py
# -*- coding: utf-8 -*-
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.core.exceptions import ObjectDoesNotExist


class MoviesCategory(models.Model):
    dsc_category = models.CharField(max_length=100, verbose_name='Category')
    sum_likes = models.IntegerField(default=0, verbose_name='Total Likes')
    sum_dislikes = models.IntegerField(default=0, verbose_name='Total Dislikes')
    ranking = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='Ranking')

    class Meta:
        db_table = 'movies_category'
        verbose_name = 'Movies Category'
        verbose_name_plural = 'Movies Category'

    def __str__(self):
        return self.dsc_category


class Movies(models.Model):
    fk_movies_category = models.ForeignKey(
        MoviesCategory, on_delete=models.CASCADE, verbose_name='Category'
    )
    dsc_movie = models.TextField(verbose_name='Movie Description')
    qtd_likes = models.IntegerField(default=0, verbose_name='Likes')
    qtd_dislikes = models.IntegerField(default=0, verbose_name='Dislikes')
    ranking = models.DecimalField(max_digits=11, decimal_places=2, verbose_name='Ranking')

    class Meta:
        db_table = 'movies'
        verbose_name = 'Movies'
        verbose_name_plural = 'Movies'


class MoviesVotes(models.Model):
    fk_movies_category = models.ForeignKey(
        MoviesCategory, on_delete=models.CASCADE, verbose_name='Category'
    )
    fk_movies = models.ForeignKey(
        Movies, on_delete=models.CASCADE, verbose_name='Movie'
    )
    # a positive value to like and a negative value to dislike
    vote_movie = models.IntegerField(default=0, verbose_name='Vote')
    date_vote = models.DateTimeField(auto_now=True,  verbose_name='Date')

    class Meta:
        db_table = 'movies_votes'
        verbose_name = 'Movies Votes'
        verbose_name_plural = 'Movies Votes'


@receiver(post_save, sender=MoviesVotes)
def movies_post_save(instance, created, **kwargs):
    if not created:
        raise Exception('PostSave: Error on save data, table Movie Votes can not be edited!')
    try:
        category = MoviesCategory.objects.get(pk=instance.fk_movies_category_id)
        movie = Movies.objects.get(pk=instance.fk_movies_id)
    except ObjectDoesNotExist:
        raise Exception(f'PostSave: Error on get categories or movies! {ObjectDoesNotExist}')
    vote = instance.vote_movie if instance.vote_movie > 0 else instance.vote_movie * -1
    if instance.vote_movie > 0:
        category.sum_likes += vote
        movie.qtd_likes += vote
    else:
        category.sum_dislikes += vote
        movie.qtd_dislikes += vote
    movie.ranking = movie.qtd_likes - (movie.qtd_dislikes / 2)
    category.ranking = category.sum_likes - (category.sum_dislikes / 2)
    try:
        movie.save()
        category.save()
    except Exception as e:
        raise Exception(f'PostSave: Error on cla ranking! - ({e})')

apps/home/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Movies, MoviesCategory


class MoviesForm(forms.ModelForm):
    fk_movies_category = forms.ModelChoiceField(
        queryset=MoviesCategory.objects.all(), label='Category'
    )
    dsc_movie = forms.CharField(
        label='Movie Description', help_text='Movie Description'
    )
    qtd_likes = forms.IntegerField(label='Likes', help_text='Likes')
    qtd_dislikes = forms.IntegerField(label='Dislikes', help_text='Dislikes')
    ranking = forms.DecimalField(
        max_digits=11, decimal_places=2, label='Ranking', help_text='Ranking'
    )

    class Meta:
        model = Movies
        fields = ('fk_movies_category', 'dsc_movie')


class MoviesCategoryForm(forms.Form):

    dsc_category = forms.CharField(label='Description')
    sum_likes = forms.IntegerField(label='Likes')
    sum_dislikes = forms.IntegerField(label='Dislikes')
    ranking = forms.DecimalField(max_digits=11, decimal_places=2, label='Ranking')

    class Meta:
        model = MoviesCategory
        fields = ('dsc_category',)
        exclude = ('qtd_likes', 'qtd_dislikes', 'ranking')

apps/home/views.py
# -*- coding: utf-8 -*-
import json
from django.http import HttpResponse
from django.views.generic.edit import DeletionMixin
from django.views.generic import TemplateView, ListView
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from .forms import MoviesForm, MoviesCategoryForm
from .models import MoviesCategory, Movies, MoviesVotes
from .mixin import UpdateMixin


class HomeView(ListView):
    template_name = 'home/index.html'
    model = Movies
    paginate_by = 8
    queryset = Movies.objects.order_by('-fk_movies_category__ranking', '-ranking')


class HomeMoviesView(DeletionMixin, UpdateMixin, TemplateView):
    form_class = MoviesForm
    template_name = 'home/movies.html'
    success_url = 'home:index'
    http_method_names = ['get', 'post', 'delete', 'put', 'path']
    pk = None

    def initial_data(self):
        data = {
            'dsc_movie': '',
            'qtd_likes': 0,
            'qtd_dislikes': 0,
            'ranking': 0.00
        }
        if self.pk is not None:
            instance = Movies.objects.get(id=self.pk)
            data['fk_movies_category'] = instance.fk_movies_category
            data['dsc_movie'] = instance.dsc_movie
            data['qtd_likes'] = instance.qtd_likes
            data['qtd_dislikes'] = instance.qtd_dislikes
            data['ranking'] = instance.ranking
        return data

    def get(self, request, pk=None, *args, **kwargs):
        self.pk = pk
        init_data = self.initial_data()
        form = self.form_class(init_data)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        self.pk = kwargs.get('pk')
        form = self.form_class(request.POST or None)
        if form.is_valid():
            if self.pk is None:
                instance = Movies()
            else:
                instance = Movies.objects.get(pk=self.pk)
            instance.fk_movies_category = form.cleaned_data['fk_movies_category']
            instance.dsc_movie = form.cleaned_data['dsc_movie']
            instance.qtd_likes = form.cleaned_data['qtd_likes']
            instance.qtd_dislikes = form.cleaned_data['qtd_dislikes']
            instance.ranking = form.cleaned_data['ranking']
            instance.save()
            return redirect(self.success_url)
        return render(request, self.template_name, {"form": form})

    def delete(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            movie = Movies.objects.get(id=pk)
            movie.delete()
        return redirect(self.success_url)

    def put(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            movie = Movies.objects.get(pk=pk)
            category = MoviesCategory.objects.get(pk=movie.fk_movies_category_id)
            vote = MoviesVotes(
                fk_movies=movie, fk_movies_category=category, vote_movie=1
            )
            vote.save()
        return redirect(self.success_url)

    def path(self, request, pk=None, *args, **kwargs):
        if pk is not None:
            movie = Movies.objects.get(pk=pk)
            category = MoviesCategory.objects.get(pk=movie.fk_movies_category_id)
            vote = MoviesVotes(
                fk_movies=movie, fk_movies_category=category, vote_movie=-1
            )
            vote.save()
        return redirect(self.success_url)


class MoviesCategoryView(TemplateView):
    template_name = 'home/category.html'
    form_class = MoviesCategoryForm
    pk = None

    def initial_data(self):
        data = {
            'dsc_category': '',
            'sum_likes': 0,
            'sum_dislikes': 0,
            'ranking': 0.00
        }
        if self.pk is not None:
            instance = MoviesCategory.objects.get(id=self.pk)
            data['dsc_category'] = instance.dsc_category
            data['sum_likes'] = instance.sum_likes
            data['sum_dislikes'] = instance.sum_dislikes
            data['ranking'] = instance.ranking
        return data

    def get(self, request, pk=None, *args, **kwargs):
        self.pk = pk
        form = self.form_class(self.initial_data())
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        self.pk = kwargs.get('pk')
        form = self.form_class(request.POST or None)
        if form.is_valid():
            if self.pk is None:
                instance = MoviesCategory()
            else:
                instance = MoviesCategory.objects.get(pk=self.pk)
            instance.dsc_category = form.cleaned_data['dsc_category']
            instance.sum_likes = form.cleaned_data['sum_likes']
            instance.sum_dislikes = form.cleaned_data['sum_dislikes']
            instance.ranking = form.cleaned_data['ranking']
            instance.save()
            return HttpResponse(
                '<script>opener.MoviesEvents.closeWindow(window, ' +
                f'"{instance.pk}", "{instance}", "#id_fk_movies_category");</script>'
            )
        return render(request, self.template_name, {"form": form})

templates/home/category.html
{% extends 'base.html' %}

{% load static %}

{%block title %}Django MongoDB CRUD{% endblock %}
{%block pagetitle %}Register Categories{% endblock %}

	{% block content %}
		<div class="row border border-white">
			<div class="center-left col-3"></div>
			<div class="col-6">
				<form method='POST' action='' enctype="multipart/form-data" id="category-form">
					{% csrf_token %}
					<h4 class="subtitle mb-2">Category</h4>
					<div class="row mb-2">
						<div class="col-4">
							<label for="dsc_category" class="control-label">Description</label>
						</div>
						<div class="col-8">
							{{form.dsc_category}}
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-4">
							<label for="sum_likes" class="control-label">Likes</label>
						</div>
						<div class="col-8">
							{{form.sum_likes}}
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-4">
							<label for="sum_dislikes" class="control-label">Dislikes</label>
						</div>
						<div class="col-8">
							{{form.sum_dislikes}}
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-4">
							<label for="ranking" class="control-label">Ranking</label>
						</div>
						<div class="col-8">
							{{form.ranking}}
						</div>
					</div>
					<div class="row mb-2">
						<div class="col-12 text-center">
							<button id="btn-submit" class="btn btn-outline-primary">
								<icon class="fas fa-database">&nbsp;Save&nbsp;</icon>
							</button>
						</div>
					</div>
				</form>
			</div>
			<div class="center-left col-3"></div>
		</div>
	{% endblock %}
{% block script %}
	<script type="text/javascript">
		var onClose = function (e) {

		}

		$(document).ready(function() {
			$('#btn-submit').click(function (e) {
				e.preventDefault();
				$('#category-form').submit();
				return False;
			});
		});
	</script>
{% endblock %}

templates/home/index.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/home/index.css' %}?version=2" >
{% endblock %}

{%block title %}Django MongoDB CRUD{% endblock %}
{%block pagetitle %}List of Movies{% endblock %}
    {% block content %}
        <div class="row">
            <div class="col-12 subtitle text-center">
                <a href="{% url 'home:movies' %}">
                    <div class="row">
                        <div class="col-6"></div>
                        <div class="col-2">
                            Add New Movie
                        </div>
                        <div class="col-1">
                            <icon class="fas fa-plus btn btn-outline-success"></icon>
                        </div>
                        <div class="col-3"></div>
                    </div>
                </a>
            </div>
        </div>
        {% if movies_list %}
        <div class="row">
            <div class="col-1"></div>
            <div class="col-10 list-items">
                <table>
                    <tr class="text-center">
                        <th class="ml-4 mr-4">Category</th>
                        <th class="ml-4 mr-4">Total</th>
                        <th class="ml-4 mr-4">ID</th>
                        <th class="ml-4 mr-4">Movie Description</th>
                        <th class="ml-4 mr-4">likes</th>
                        <th class="ml-4 mr-4">dislikes</th>
                        <th class="ml-4 mr-4">ranking</th>
                        <th class="ml-4 mr-4">operations</th>
                    </tr>
                    {% regroup movies_list by fk_movies_category.dsc_category as category_list %}
                    {% for category, movies in category_list %}
                    <tr>
                        <td class="text-warning category-col" width="200">
                            {{ category }}
                        </td>
                        <td>
                            {{ movies.0.fk_movies_category.ranking }}
                        </td>
                        {% for movie in movies %}
                            <td>{{ movie.id }}</td>
                            <td width="500">
                                <a class="edit-movie" data-link="{% url 'home:movies' %}{{ movie.id }}" href="">
                                    {{ movie.dsc_movie }}
                                </a>
                            </td>
                            <td>
                                {{ movie.qtd_likes }}
                            </td>
                            <td>
                                {{ movie.qtd_dislikes }}
                            </td>
                            <td>{{ movie.ranking }}</td>
                            <td class="p-0 m-0 text-center" width="120">
                                <icon data-link="{% url 'home:movies' %}{{ movie.id }}" class="far fa-thumbs-up p-2 ilike"></icon>
                                <icon data-link="{% url 'home:movies' %}{{ movie.id }}" class="far fa-thumbs-down p-2 idislike"></icon>
                                <icon data-link="{% url 'home:movies' %}{{ movie.id }}" class="far fa-trash-alt idelete-movie p-2"></icon>
                            </td>
                        </tr>
                        {% if movies|last != movie %}
                        <tr>
                            <td colspan="2"></td>
                        {% endif %}
                        {% endfor %}
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="col-1"></div>
        </div>
        {% if is_paginated %}
        <div class="row text-center mt-2">
            <div class="col-1"></div>
            <div class="col-10">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link" >&laquo;</span>
                        </li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="page-item active">
                                <span class="page-link" >{{ i }} <span class="sr-only">(current)</span></span>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a  class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-1"></div>
        </div>
        {% endif %}
        {% else %}
            <p>There are no books in the library.</p>
        {% endif %}
    {% endblock %}
    {% block script %}
	<script type="text/javascript" src="{% static 'js/home/index.js' %}"></script>
    {% endblock %}

templates/home/movies.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
	<link rel="stylesheet" href="{% static 'css/home/movies.css' %}?version=2" >
{% endblock %}

{%block title %}Django MongoDB CRUD{% endblock %}
{%block pagetitle %}Register Movies{% endblock %}

	{% block content %}
		<div class="row">
			<div class="center-left col-3"></div>
			<div class="col-6">
				<div class="row">
					<div class="col-12 text-center">
						<div class="subtitle">
							<h3>New Movie</h3>
						</div>
					</div>
				</div>
				<form method="POST" class="post-form">
					{% csrf_token %}
					<div class="row mb-2">
						<div class="col-4">
							<label for="fk_movies_category" class="control-label">Movie Category</label>
						</div>
						<div class="col-8">
							{{form.fk_movies_category }}
							<a data-link="{% url 'home:category' %}" id="add-category">
								<icon class="fas fa-plus ml-3 mr-2 p-1 add-category"></icon>
							</a>
							<a data-link="{% url 'home:category' %}" id="edit-category">
								<icon class="fas fa-pencil-alt p-1 edit-category"></icon>
							</a>
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-4">
							<label for="dsc_movie" class="control-label">Movie Description</label>
						</div>
						<div class="col-8">
							{{form.dsc_movie }}
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-4">
							<label for="qtd_likes" class="control-label">Likes</label>
						</div>
						<div class="col-8">
							{{form.qtd_likes }}
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-4">
							<label for="qtd_dislikes" class="control-label">Dislikes</label>
						</div>
						<div class="col-8">
							{{form.qtd_dislikes }}
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-4">
							<label for="ranking" class="control-label">Ranking</label>
						</div>
						<div class="col-8">
							{{form.ranking }}
						</div>
					</div>

					<div class="row mb-2">
						<div class="col-12 text-center">
							<button class="btn-back btn btn-outline-warning mr-5">
								<icon class="fas fa-home">&nbsp;Home&nbsp;</icon>
							</button>
							<button type="submit" class="btn-save btn btn-outline-primary">
								<icon class="fas fa-database">&nbsp;Save&nbsp;</icon>
							</button>
						</div>
					</div>
				</form>
			</div>
			<div class="center-right col-3"></div>
		</div>
	{% endblock %}

{% block script %}
	<script type="text/javascript" src="{% static 'js/home/movies.js' %}"></script>
{% endblock %}